package cn.uestc.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.teacher_id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.teacher_id
     *
     * @return the value of t_student.teacher_id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.teacher_id
     *
     * @param teacherId the value for t_student.teacher_id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}