package cn.uestc.bean;

public class Teacher {
    @Override
    public String toString() {
        return "Teacher{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", lesson='" + lesson + '\'' +
                '}';
    }

    public Teacher() {
    }

    public Teacher(Integer id, String name, String lesson) {
        this.id = id;
        this.name = name;
        this.lesson = lesson;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.lesson
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    private String lesson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.name
     *
     * @return the value of t_teacher.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.name
     *
     * @param name the value for t_teacher.name
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.lesson
     *
     * @return the value of t_teacher.lesson
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public String getLesson() {
        return lesson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.lesson
     *
     * @param lesson the value for t_teacher.lesson
     *
     * @mbggenerated Sun Feb 14 23:56:34 CST 2021
     */
    public void setLesson(String lesson) {
        this.lesson = lesson == null ? null : lesson.trim();
    }
}